name: Backend CI Pipeline

# Trigger the workflow on pull requests assigned to the 'main' branch,
# manual dispatch, and pushes to 'main' or any 'dev/**' branches.
on:
  pull_request:
    types:
      - assigned
    branches:
      - main

  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev/**'

jobs:
  Gradle-Build-and-Test:
    # Define the job to run on the latest Ubuntu environment.
    runs-on: ubuntu-latest
    environment: backend-test-dev
    steps:
      # Step to check out the repository code.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step to set up JDK 17 using the Temurin distribution.
      - name: Set up JDK 17
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step to grant execute permissions to the Gradle wrapper script.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step to build the project using Gradle.
      - name: Build with Gradle
        run: ./gradlew build

      # Step to run tests and generate a code coverage report using Gradle.
      - name: Run tests
        run: ./gradlew test jacocoTestReport

      # Step to upload the test results as an artifact.
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      # Step to upload the code coverage report as an artifact.
      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

  Sonarcloud-Scan:
    # Define the job to run after the 'Gradle-Build-and-Test' job.
    needs: Gradle-Build-and-Test
    runs-on: ubuntu-latest
    environment: backend-test-dev
    steps:
      - name: Check Branch Name
        run: echo "Branch name is ${{ github.ref_name }}"
      # Step to perform a SonarCloud scan using the provided environment variables.
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.java.coveragePlugin=jacoco
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.branch.name=${{ github.ref_name }}

  Build-and-Push-image-to-DockerHub:
    # Define the job to run after the 'Sonarcloud-Scan' job.
    needs: Sonarcloud-Scan
    runs-on: ubuntu-latest
    environment: backend-test-dev
    steps:
      # Step to check out the repository code.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step to log in to Docker Hub using the provided credentials.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step to build and push the Docker image with a timestamp tag and branch-specific latest tag.
      - name: Build and push Docker image
        run: |
          # Set the timezone
          export TZ=Asia/Kolkata

          # Generate the timestamp for the image tag
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          # Get the branch name, replace '/' with '-'
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')

          # Define the image tag with the timestamp
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-${TIMESTAMP}

          # Define the latest tag specific to the branch
          LATEST_TAG=${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-latest

          # Build the Docker image with both the timestamped and latest tags
          docker build -t ${IMAGE_TAG} -t ${LATEST_TAG} .

          # Push both the timestamped and latest images to the Docker registry
          docker push ${IMAGE_TAG}
          docker push ${LATEST_TAG}
          
  Update-manifests:
    if: github.ref == 'refs/heads/main'
    needs: Build-and-Push-image-to-DockerHub
    runs-on: ubuntu-latest
    environment: backend-test-dev
    steps:
      - name: Checkout K8s Manifests Repository
        uses: actions/checkout@v4
        with:
          repository: yadnesh082024/spring-boot-backend-k8s-manifests
          token: ${{ secrets.GH_PAT_UPDATE_MANIFEST }}
          path: spring-boot-backend-helm-chart

      - name: Verify file existence
        run: ls -l values.yaml

      - name: Update Helm values
        run: |
          sed -i 's/tag: .*/tag: main-latest/' values.yaml

      - name: Commit and push changes
        run: |
          cd helm-charts
          git config --global user.email yadnesh082024@gmail.com
          git config --global user.name yadnesh
          git add .
          git commit -m "Update image tag to main-latest"
          git push origin main